openapi: 3.0.1
info:
  title: Product API
  description: Product Microservices
  version: "2.0"
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:

  /addProduct:
    post:
      tags:
        - product-controller
      operationId: addProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'

  /products:
    get:
      tags:
        - product-controller
      operationId: findAllProducts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /productById/{id}:
    get:
      tags:
        - product-controller
      operationId: findProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'

  /product/{name}:
    get:
      tags:
        - product-controller
      operationId: findProductByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'

                /update:
                  put:
                    tags:
                      - product-controller
                    operationId: updateProduct
                    parameters:
                      - name: id
                        in: path
                        required: true
                        schema:
                          type: integer
                          format: int64
                    requestBody:
                      content:
                        application/json:
                          schema:
                            $ref: '#/components/schemas/Product'
                      required: true
                    responses:
                      "200":
                        description: OK
                        content:
                          '*/*':
                            schema:
                              $ref: '#/components/schemas/Product'

  /delete/{id}:
    delete:
      tags:
        - product-controller
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        prodName:
          type: string
        prodQuan:
          type: integer
        prodPrice:
          type: long